### ISSUE TITLE
Getting Error: Cannot read property 'Embed' of undefined

### ISSUE THREAD

**Issue by jorgepuerta00** [moonstar-x/react-twitch-embed#25] opened 2020-09-04 16:05 UTC
![Screenshot_1](https://user-images.githubusercontent.com/27908934/92261131-90372d00-ee9e-11ea-90cc-227fc9c9c853.png)

**Comment by moonstar-x** [comment] 2020-09-04 16:16
Hey there, quick questions:
1. Are you using any sort of server side rendering or just plain React?
2. If you open the Network inspector of your browser, do you see a request to the following URL: `https://player.twitch.tv/js/embed/v1.js`?
3. I see the trace shows the error in a file that is not inside node_modules, Are you trying to use the source code directly or are you using the package from npm? (which is packed and transpiled to work in the browser since it's written in ES6 and browser js does not recognize the `import` statement which is probably what's causing this issue).

**Comment by SeanMuggin** [comment] 2021-11-12 04:06
![image](https://user-images.githubusercontent.com/38870781/141407118-2f5675b0-3307-47bf-982d-f80d6331ea0c.png)

I am getting same error. I too notice that it shows the TwitchEmbed.js in my src/components folder however it does not live there in my file structure and the method that is failing seems to live in node_modules.

![image](https://user-images.githubusercontent.com/38870781/141407601-e07573f4-f61e-42f0-9f11-d5dec8e710ea.png)


![image](https://user-images.githubusercontent.com/38870781/141407523-e981df24-02a5-476d-8ceb-10fb9c9e8eb6.png)
![image](https://user-images.githubusercontent.com/38870781/141407548-e464e995-14e4-49a7-9e78-9944e86e736d.png)

**Comment by moonstar-x** [comment] 2021-11-12 04:16
Hey, the error path seems kinda weird, I don't see why it would display an incorrect file.

In any case, are you doing any server side rendering or using web components?

In the network inspector in your browser, do you see any request to `https://player.twitch.tv/js/embed/v1.js`?

**Comment by SeanMuggin** [comment] 2021-11-12 04:21
It worked as soon as I changed it off of your channel haha

**Comment by moonstar-x** [comment] 2021-11-12 04:24
That's really weird.

Can you answer me this before you go?

Do you remember visiting any other site that embeds Twitch before?

Was this the very first time that you've tried displaying the Embed component on your page?

I'm suspecting that the way the embed script is being downloaded is actually flawed and only works for subsequent visits because the script is already cached on the browser.

**Comment by SeanMuggin** [comment] 2021-11-12 04:27
I tried running with the suggested code snippet on Twitch docs 

![image](https://user-images.githubusercontent.com/38870781/141409561-c8ad751e-7d5a-4875-9193-c858bbde3d07.png)

**Comment by moonstar-x** [comment] 2021-11-12 04:28
You put that snippet of code inside a React component?

**Comment by SeanMuggin** [comment] 2021-11-12 04:29
I just made it a function and called it with JSX style inline. I don't even think I had it syntactically correct

**Comment by SeanMuggin** [comment] 2021-11-12 04:31
More likely due to the other suggestion you had of visiting another site that had an embedded player. Notice the edit I made to original response about having saltybet open in the browser

**Comment by SeanMuggin** [comment] 2021-11-12 04:36
I actually seem to be getting that error intermittently now... and while I got you available adding the  ' withChat="false" ' prop doesn't seem to be removing the chat from the player for me . 

![image](https://user-images.githubusercontent.com/38870781/141410276-e5646325-70bc-4c1a-8f2a-8afe2bc018e3.png)

**Comment by moonstar-x** [comment] 2021-11-12 04:37
> I just made it a function and called it with JSX style inline. I don't even think I had it syntactically correct
> 
> 

I'm actually not 100% if I understood correctly how you implemented it.

In any case, the error was probably due to the script tag being inside the React component, sure the script gets downloaded as soon as the script tag is present in the DOM, the problem is that it needs to wait for the script to download before actually using it.

Some of the code snippets from the twitch docs would probably not work in React straight out of the box because they're really designed for HTML in mind.

**Comment by moonstar-x** [comment] 2021-11-12 04:38
As for the `withCha` prop, make sure you're passing a boolean and not a string, so it should be `withChat={false}`.

**Comment by SeanMuggin** [comment] 2021-11-12 04:44
Okay last one.... 

Is this syntax correct :

` parent={['http://localhost:3000/']}`

I think this parameter should get rid of the twitch embedded player message or at least it should in prod but I get 

![image](https://user-images.githubusercontent.com/38870781/141411058-e8f81826-abe6-47d9-9c10-fa80987a4c98.png)

**Comment by moonstar-x** [comment] 2021-11-12 04:54
No, technically it should be `parent={['localhost']}` because you're supposed to pass the domain and not the url of your site.

However, this is unnecessary because twitch technically does not have this requirement for localhost.

I actually don't know what message are you talking about, is it this one? 

![image](https://discuss.dev.twitch.tv/uploads/default/original/2X/f/feab18189d1deafcc3b795f9cc1d13c2d656675a.jpeg)

**Comment by SeanMuggin** [comment] 2021-11-12 05:13
Yeah that is the message I am talking about. 

I am hitting our original error again :/ 

![image](https://user-images.githubusercontent.com/38870781/141413396-f64b033d-048b-4771-8c2d-6d4b65d155bc.png)

I think it first occured again when I opened saltybet again in another tab but I have tried closing saltybet (the other website with an embedded player) and running localhost in a private browser which should have taken care of the cache but still getting this

**Comment by moonstar-x** [comment] 2021-11-12 05:32
Actually, I'm afraid that screen is there to stay, you will get it randomly from time to time. Somebody already reported this in #35 but there really isn't anything that we can do, Twitch really wants to keep its viewers on their site rather than having them from other ones. In fact, this message will pop up again and again every x minutes.

As for the error, I stilk don't know what may be causing it.

As a workaround, I would imagine that you could add inside `public/index.html`:

```
<script src="https://embed.twitch.tv/embed/v1.js"></script>
```

This should download the twitch embed script immediately. It isn't that ideal because it will download the script even when no component needs it.

**Comment by SeanMuggin** [comment] 2021-11-12 05:46
That worked! Thank you!!

**Comment by moonstar-x** [comment] 2022-08-22 04:51
Hi there, sorry for the long hiatus.

I'm gonna close this issue due to inactivity. However, I have just updated this package to version `3.0.1` with #37.

Any reference to `window` or `document` have been moved to `useEffect()` which should be executed in the client for SSR apps.

If you feel this was a mistake, feel free to re-open this issue.

Thanks!

**Closed by moonstar-x** 2022-08-22 04:51 UTC
